CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50),
	email VARCHAR(100) UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)


CREATE TABLE posts (
	id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES users(id),
	title VARCHAR(50),
	content TEXT, 
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
